money_splitter/expenses/urls.py
from django.urls import path
from . import views
#app_name = 'expenses'
urlpatterns = [
    path('<int:pk>/', views.expense_list, name='expense_list'),
    path('<int:pk>/create/', views.create_expense, name='create_expense'),
    path('<int:expense_id>/<int:group_id>/split/', views.split_expense, name='split_expense'),
    path('net_owed/<int:group_id>/', views.net_amount_owed, name='net_amount_owed')
]

money_splitter/groups/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.group_list, name='group_list'),
    path('create/', views.create_group, name='create_group'),
    path('join/', views.join_group, name='join_group'),
]

money_splitter/money_splitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
    path('expenses/', include(('expenses.urls', 'expenses'), namespace='expenses')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
]

money_splitter/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
]

money_splitter/groups/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User

CustomUser = get_user_model()


# class Group(models.Model):
#     name = models.CharField(max_length=100)
#     members = models.ManyToManyField(User, related_name='groups')
#     creator = models.ForeignKey(User, on_delete=models.CASCADE,
#                                 related_name='created_groups')
class Group(models.Model):
    name = models.CharField(max_length=100)
    creator = models.ForeignKey(CustomUser, on_delete=models.CASCADE,
                                related_name='created_groups')
    members = models.ManyToManyField(CustomUser, related_name='member_groups')

    def __str__(self):
        return self.name

money_splitter/groups/forms.py
from django import forms
from .models import Group


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ['name']

class GroupIdForm(forms.Form):
    group_id = forms.IntegerField(label='Group ID')

money_splitter/groups/views.py
# Create your views here.
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Group
from .forms import GroupForm, GroupIdForm


@login_required
def group_list(request):
    groups = Group.objects.filter(members=request.user)
    return render(request, 'groups/group_list.html', {'groups': groups})


@login_required
def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST)
        if form.is_valid():
            group = form.save(commit=False)
            group.creator = request.user
            group.save()
            group.members.add(request.user)
            return redirect('groups:group_list')
    else:
        form = GroupForm()
    return render(request, 'groups/create_group.html', {'form': form})



@login_required
def join_group(request):
    if request.method == 'POST':
        form = GroupIdForm(request.POST)
        if form.is_valid():
            group_id = form.cleaned_data['group_id']
            group = get_object_or_404(Group, id=group_id)
            group.members.add(request.user)
            return redirect('groups:group_list')
    else:
        form = GroupIdForm()
    return render(request, 'groups/join_group.html', {'form': form})

money_splitter/groups/templates/groups/create_group.html
{% extends "groups/base_generic.html" %}

{% block content %}
  <h1>Create Group</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>
  <a href="{% url 'groups:group_list' %}">Back</a>
{% endblock %}

money_splitter/groups/templates/groups/group_list.html
{% extends "groups/base_generic.html" %}

{% block content %}
  <h1>Groups</h1>
  <a href="{% url 'groups:create_group' %}">Create Group</a>
  <a href="join/">Join Group </a>
  <ul>
    {% for group in groups %}
      <li>
        <a href="{% url 'expenses:expense_list' group.id %}">{{ group.name }}  </a>
<!--         <span style="margin-right: 20px;"></span>-->

      </li>
    {% endfor %}
  </ul>


{% endblock %}

money_splitter/groups/templates/groups/join_group.html
{% extends "groups/base_generic.html" %}
{% block content %}

<h2>Join a Group</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Join Group</button>
</form>

{% endblock %}