money_splitter/expenses/urls.py
from django.urls import path
from . import views
#app_name = 'expenses'
urlpatterns = [
    path('<int:pk>/', views.expense_list, name='expense_list'),
    path('<int:pk>/create/', views.create_expense, name='create_expense'),
    path('<int:expense_id>/<int:group_id>/split/', views.split_expense, name='split_expense'),
    path('net_owed/<int:group_id>/', views.net_amount_owed, name='net_amount_owed')
]

money_splitter/groups/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.group_list, name='group_list'),
    path('create/', views.create_group, name='create_group'),
    path('join/', views.join_group, name='join_group'),
]

money_splitter/money_splitter/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('groups/', include(('groups.urls', 'groups'), namespace='groups')),
    path('expenses/', include(('expenses.urls', 'expenses'), namespace='expenses')),
    path('payments/', include(('payments.urls', 'payments'), namespace='payments')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
]

money_splitter/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
]

money_splitter/expenses/models.py
from datetime import timezone, datetime

from django.db import models
from django.contrib.auth.models import User
from groups.models import Group

class Expense(models.Model):
    name = models.CharField(max_length=100, default=None)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name='created_expenses', default=None)
    group = models.ForeignKey(Group, on_delete=models.CASCADE, related_name='expenses', default=None)
    split_method = models.CharField(max_length=10, choices=(('equal', 'Equal'), ('custom', 'Custom')), default='default_value')
    created_at = models.DateTimeField(auto_now_add=True, null=True)


    def __str__(self):
        return self.name

money_splitter/expenses/forms.py
from django import forms
from .models import Expense

class ExpenseForm(forms.ModelForm):
    class Meta:
        model = Expense
        fields = ['name', 'amount', 'split_method']

money_splitter/expenses/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Expense
from payments.models import Payment
from .forms import ExpenseForm
from groups.models import Group
from users.models import CustomUser
from django.contrib.auth import get_user_model


@login_required
def expense_list(request, pk):
    expenses = Expense.objects.filter(group=pk)
    group_name = Group.objects.get(id=pk).name

    return render(request, 'expenses/expense_list.html',
                  {'expenses': expenses, 'id': pk, 'group_name': group_name})

    # total = []
    # payment_to_names = []
    # group = Group.objects.get(id=pk)
    #
    # # payment_to_id_list = Payment.objects.filter(
    # #     paidby_id=request.user.id, expense__group=group
    # # ).paidto_id
    #
    # payment_to_id_list = Payment.objects.filter(
    #     paidby_id=request.user.id, expense__group=group
    # ).values_list('paidto_id', flat=True).distinct()
    #
    # # payment_to_id_list = Payment.objects.filter(
    # #     paidby_id=request.user.id, expense__group=group
    # # ).paid_to_name
    #
    # for payment_to_id in payment_to_id_list:
    #     if request.user.id == payment_to_id:
    #         continue
    #     total_due = calculate_total_due(request, request.user.id, payment_to_id, pk)
    #     total.append(total_due)
    #     payment_to_names.append(get_user_model().objects.get(id=payment_to_id).username)
    #
    # l = list(zip(payment_to_names, total))
    # return render(request, 'expenses/expense_list.html',
    #               {'expenses': expenses, 'id': pk, 'group_name': group_name,
    # 'l': total})


# def calculate_total_due(request, paid_by_id, paid_to_id, group_id):
#     # paid_by = CustomUser.objects.get(id=paid_by_id)
#     # paid_to = CustomUser.objects.get(id=paid_to_id)
#     group = Group.objects.get(id=group_id)
#
#     payments_from_paid_by_to_paid_to = Payment.objects.filter(
#         paidby_id=paid_by_id, paidto_id=paid_to_id, expense__group=group
#     )
#     payments_from_paid_to_to_paid_by = Payment.objects.filter(
#         paidby_id=paid_to_id, paidto_id=paid_by_id, expense__group=group
#     )
#
#     total_due = sum(
#         [payment.amount for payment in payments_from_paid_by_to_paid_to]) - sum(
#         [payment.amount for payment in payments_from_paid_to_to_paid_by])
#
#     return total_due


@login_required
def net_amount_owed(request, group_id):
    # user = CustomUser.objects.get(id=user_id)
    user = request.user.id
    # group = user.member_groups.first()
    group = Group.objects.get(id=group_id)
    # members = group.members.exclude(id=user.id)
    payments = Payment.objects.filter(paidto_id=user, expense__group=group)
    # total_paid = sum([p.amount for p in payments])
    # net_owed = total_paid - sum([p.paid_to.amount_owed for p in payments])

    net_owed = {}
    names = {}

    amount_name_list = []
    for p in payments:
        if p.paidby_id not in net_owed:
            net_owed[p.paidby_id] = -p.amount
            names[p.paidby_id] = p.paid_by_names

        else:
            net_owed[p.paidby_id] -= p.amount

    payments = Payment.objects.filter(paidby_id=user, expense__group=group)
    for p in payments:
        if p.paidto_id not in net_owed:
            net_owed[p.paidto_id] = p.amount
            names[p.paidto_id] = p.paid_to_names

        else:
            net_owed[p.paidto_id] += p.amount

    for (key1, value1), (key2, value2) in zip(net_owed.items(), names.items()):
        if value1 != 0:
            amount_name_list.append({'amt': value1, 'name': value2})

    return render(request, 'expenses/net_amount_owed.html',
                  {'user': user, 'group': group,
                   'amount_name_list': amount_name_list})


@login_required
def create_expense(request, pk):
    expense = None
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            expense = form.save(commit=False)
            expense.creator = request.user
            expense.group_id = pk
            expense.save()
            split_exp(request, expense_id=expense.id)
            # split_expense(request , expense.id)
            # return redirect('expenses:expense_list', pk=pk)
    else:
        form = ExpenseForm()
    return render(request, 'expenses/create_expense.html',
                  {'form': form, 'id': pk, 'expense': expense})


# def split_expense(request , expense_id):
#     expense = Expense.objects.get(id=expense_id)
#     if expense.split_method == 'equal':
#         split_equal(request , expense)
#
# def split_equal(request , expense):
#     total_amount = expense.amount
#     members = expense.group.members.all()
#     member_count = members.count()
#     amount_per_member = total_amount / member_count
#     user_paid_by = User.objects.get(username='username1')
#     user_paid_to = User.objects.get(username='username2')
#     for member in members:
#         payment = Payment(amount=amount_per_member, expense=expense,
#                           paid_by=request.user, paid_to=member)
#         payment.save()
#     expense.delete()
#
def split_exp(request, expense_id):
    expense = Expense.objects.get(id=expense_id)

    members = expense.group.members.all()
    split_amount = expense.amount / members.count()
    for member in members:
        # if member == expense.creator:
        # continue
        payment = Payment()
        payment.expense = expense
        payment.amount = split_amount
        # payment.paid_to = member
        # payment.paid_by = expense.creator
        payment.paid_by_names = member.username
        payment.paid_to_names = expense.creator.username
        payment.paidby_id = member.id
        payment.paidto_id = expense.creator.id

        payment.save()


def split_expense(request, expense_id, group_id):
    payments = Payment.objects.filter(expense_id=expense_id)
    ppp = payments[0].paid_by_names
    return render(request, 'expenses/split_expense.html',
                  {'payments': payments, 'id': group_id, 'ppp': ppp,
                   'Total': Expense.objects.get(id=expense_id)})

money_splitter/expenses/templates/expenses/about.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>About Us | Splitto-4-Kiddo</title>
  <link rel="shortcut icon" type="image/png" href="./img/money.jpg" />
  <link rel="stylesheet" href="expensestyle.css" />
</head>

<body>
  <header>
    <nav class="nav">
      <img src="./img/money.jpg" alt="Splitto-4-Kiddo logo" class="nav__logo" id="logo" designer="Sam"
        data-version-number="3.0" />
      <ul class="nav__links">
        <li class="nav__item">
          <a class="nav__link nav__link--btn btn--show-modal" href="../../../users/templates/users/index.html">Home</a>
        </li>
        <li class="nav__item">
          <a class="nav__link nav__link--btn btn--show-modal" href="terms.html">Terms of Use</a>
        </li>
        <li class="nav__item">
          <a class="nav__link nav__link--btn btn--show-modal" href="privacy.html">Privacy Policy</a>
        </li>
        <li class="nav__item">
          <a class="nav__link nav__link--btn btn--show-modal" href="blog.html">Blog</a>
        </li>
      </ul>
    </nav>
  </header>
  <section class="section" id="section--3">
    <div class="section__title section__title--testimonials">
      <h1><u>About Us</u></h1>
    </div>
    <div class="slider">
      <div class="slide">
        <div class="testimonial">
          <h5 class="testimonial__header"> Why We Chose This Project:</h5>
          <blockquote class="testimonial__text">
            Splitto-4-Kiddo is our chosen project, driven by a shared recognition of the universal challenges in
            managing shared expenses within social circles. We are committed to simplifying expense splitting for
            everyone, irrespective of age or background.
            Focused on addressing a common pain point in financial collaboration across diverse groups, Splitto-4-Kiddo
            provides a digital solution to streamline expense splitting. By fostering transparency and easing the
            complexities associated with shared financial responsibilities, we aim to empower individuals and groups.
            Our team believes in the transformative power of technology. Splitto-4-Kiddo represents our dedication to
            creating a user-friendly platform, prioritizing accessibility, and contributing to building harmonious
            connections within communities. It's our commitment to making a positive impact by addressing the universal
            need for streamlined, transparent, and hassle-free expense management.
          </blockquote>
          <address class="testimonial__author"></address>
          <img src="img/Ritam.jpg" alt="" class="testimonial__photo" />
          <h6 class="testimonial__name">Ritam Bhattacharya</h6>
        </div>
      </div>

      <div class="slide">
        <div class="testimonial">
          <h5 class="testimonial__header">
            Empower everyone to give food effortlessly.
          </h5>
          <blockquote class="testimonial__text">
            What We Are Solving:
            At Splitto-4-Kiddo, we address the challenges of shared expense management for everyone. Whether it's
            splitting bills among friends, roommates, or colleagues, our platform provides a streamlined solution. We
            simplify the process by offering a user-friendly interface to effortlessly add members, record debts, and
            clarify who owes whom.

            The common complexities of manual calculations and misunderstandings are alleviated through Splitto-4-Kiddo,
            promoting transparency and fairness within social circles. By focusing on accessibility and ease of use, our
            platform empowers individuals and groups to navigate shared expenses seamlessly. Splitto-4-Kiddo transforms
            the often intricate task of expense tracking into a stress-free experience, making financial collaboration
            clear, accessible, and equitable for users from all walks of life.
          </blockquote>
          <address class="testimonial__author">
            <img src="img/subhojit.jpg" alt="" class="testimonial__photo" />
            <h6 class="testimonial__name">Subhojit Guin</h6>
          </address>
        </div>
      </div>

      <div class="slide">
        <div class="testimonial">
          <h5 class="testimonial__header">A hunger-free world
          </h5>
          <blockquote class="testimonial__text">
            Our Future Ambitions:
            At Splitto-4-Kiddo, our vision extends beyond simplifying shared expenses. We aim to broaden our impact
            globally, connecting individuals and groups across regions. Our ambition is to facilitate seamless expense
            splitting internationally, making financial collaboration accessible and transparent.

            We also aspire to be pioneers in raising awareness about responsible financial practices. By educating
            users, we aim to contribute to a global community where shared expense management is not just simplified but
            also aligned with ethical and transparent principles.

            As we evolve, our commitment remains unwavering – to create a future where Splitto-4-Kiddo is synonymous
            with accessible, equitable, and seamless financial collaboration, fostering harmony among diverse
            communities worldwide.

          </blockquote>
          <address class="testimonial__author">
            <img src="img/samanyu.jpg" alt="" class="testimonial__photo" />
            <h6 class="testimonial__name">Samanyu Deghuria</h6>
          </address>
        </div>
      </div>
      <div class="slide">
        <div class="testimonial">
          <h5 class="testimonial__header">A hunger-free world
          </h5>
          <blockquote class="testimonial__text">
            Our Future Ambitions:
            Our journey has just begun, and we have big dreams for the future. As we continue to grow and expand, we aim
            to:
            Widen Our Reach: We aspire to connect more food donors with those in need, not just locally, but across
            regions and potentially even internationally.
            Raise Awareness: We want to be at the forefront of raising awareness about food wastage and hunger,
            educating people on how they can make a positive impact.

          </blockquote>
          <address class="testimonial__author">
            <img src="img/sudhesna.jpg" alt="" class="testimonial__photo" />
            <h6 class="testimonial__name"> Sudhesna Pathak</h6>

          </address>
        </div>
      </div>

      <button class="slider__btn slider__btn--left">&larr;</button>
      <button class="slider__btn slider__btn--right">&rarr;</button>
      <div class="dots">
      </div>
    </div>
  </section>
  <script src="myjs.js"></script>
</body>

</html>

money_splitter/expenses/templates/expenses/blog.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog | Splitto-4-Kiddo</title>
    <link rel="shortcut icon" type="image/png" href="./img/money.jpg" />
    <link rel="stylesheet" href="{% static 'expensestyle.css' %}" />
</head>

<body>
    <header>
        <nav class="nav">
            <img src="./img/money.jpg" alt="Splitto-4-Kiddo logo" class="nav__logo" id="logo" designer="Sam"
                data-version-number="3.0" />
            <ul class="nav__links">
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="../../../users/templates/users/index.html">Home</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="terms.html">Terms of Use</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="privacy.html">Privacy Policy</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="about.html">About Us</a>
                </li>
            </ul>
        </nav>
    </header>
    <h1><u>Blog</u></h1>
    <div class="blog">
        <ul>
            <li>
                <h3>Smart Expense Splitting Strategies:</h3>
                <ul>
                    <li>Dive into practical tips and strategies for efficiently managing shared expenses. From group
                        trips to household bills, discover ways to simplify the process.</li>
                </ul>
            </li>
            <li>
                <h3>Financial Literacy for All Ages:</h3>
                <ul>
                    <li>Explore articles aimed at enhancing financial literacy for individuals of all ages. We believe
                        that knowledge empowers, and our blog provides valuable insights into responsible financial
                        practices.</li>
                </ul>
            </li>
            <li>
                <h3>Real Stories, Real Solutions:</h3>
                <ul>
                    <li>Connect with real-life stories of individuals and groups who have found success in using
                        Splitto-4-Kiddo. Learn how our platform has made a positive impact on their financial
                        collaboration.</li>
                </ul>
            </li>
            <li>
                <h3>Community Spotlight:</h3>
                <ul>
                    <li>Highlighting the vibrant communities that use Splitto-4-Kiddo. Learn about their experiences,
                        challenges, and how they navigate shared expenses in unique ways.</li>
                </ul>
            </li>
        </ul>
        <p>
            <h3>Join the Conversation:</h3>
            Our blog is not just a one-way street. We encourage you to join the conversation by sharing your thoughts,
            experiences, and tips. Together, let's build a community centered around financial harmony.

            Stay tuned for regular updates, expert insights, and stories that inspire financial well-being. At
            Splitto-4-Kiddo, we believe that shared finances can be a source of harmony, and our blog is here to guide
            you
            on that journey. Happy reading!
        </p>
    </div>

</body>

</html>

money_splitter/expenses/templates/expenses/create_expense.html
{% extends "expenses/base_generic.html" %}

{% block content %}

<h1>Create Expense</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
<a href="{% url 'expenses:expense_list' id %}">Back to Expense List</a>
{% if expense is not None %}
<a href="{% url 'expenses:split_expense' expense.id id %}">Split Expense</a>
{% endif %}
{% endblock %}

money_splitter/expenses/templates/expenses/createnewgroup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="expensestyle.css" />
    <title>Document</title>
</head>
<body class="add-new">
    <div class="member-table">
        <table class="table">
          <thead>
            <tr>
              <th scope="col" class="1-col">First</th>
              <th scope="col"><button type="button" class="btn">Handle</button></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td class="1stcol">Mark</td>
              <td>@mdo</td>
            </tr>
            <tr>
              <td class="1stcol">Jacob</td>
              <td>@twitter</td>
            </tr>
            <tr>
              <td class="1stcol">@fat</td>
              <td colspan="2">Larry the Bird</td>
            </tr>
          </tbody>
        </table>

      </div>

      <div class="distribution-table">
          <table class="table">
              <thead>
                <tr>
                  <th scope="col" class="1-col">First</th>
                  <th scope="col"><button type="button" class="btn">Handle</button></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="1stcol">Mark</td>
                  <td>@mdo</td>
                </tr>
                <tr>
                  <td class="1stcol">Jacob</td>
                  <td>@twitter</td>
                </tr>
                <tr>
                  <td class="1stcol">@fat</td>
                  <td colspan="2">Larry the Bird</td>
                </tr>
              </tbody>
            </table>
      </div>
      <div><button type="button" class="btn">Base class</button></div>




</body>
</html>

money_splitter/expenses/templates/expenses/expense.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
    />
    <title>Document</title>
    <link rel="stylesheet" href="expensestyle.css" />
  </head>
  <body class="expense-chart">
    <div class="member-table">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="1-col">First</th>
            <th scope="col"><button type="button" class="btn">Handle</button></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="1stcol">Mark</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <td class="1stcol">Jacob</td>
            <td>@twitter</td>
          </tr>
          <tr>
            <td class="1stcol">@fat</td>
            <td colspan="2">Larry the Bird</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="distribution-table">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" class="1-col">First</th>
            <th scope="col"><button type="button" class="btn">Handle</button></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="1stcol">Mark</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <td class="1stcol">Jacob</td>
            <td>@twitter</td>
          </tr>
          <tr>
            <td class="1stcol">@fat</td>
            <td colspan="2">Larry the Bird</td>
          </tr>
        </tbody>
      </table>
    </div>
    <div><button type="button" class="btn">Base class</button></div>
    <script
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
    ></script>
  </body>
</html>

money_splitter/expenses/templates/expenses/expense_list.html
{% extends "expenses/base_generic.html" %}

{% block content %}
  <h1>{{group_name}}: Expenses</h1>
  <h4> Group ID: {{ id }}</h4>
  <ul>
    {% for x  in l %}
    <li>{{x}}</li>
    {% endfor %}
  </ul>
  <ul>
    {% for expense in expenses %}
    <li><a href="{% url 'expenses:split_expense' expense_id=expense.id group_id=id%}">{{ expense.name }}</a> - {{ expense.amount }}</li>
    {% endfor %}
  </ul>
<a href="{% url 'expenses:create_expense' id %}">Create Expense</a>
<a href="{% url 'groups:group_list' %}">Back to Group List</a>
{% endblock %}

money_splitter/expenses/templates/expenses/net_amount_owed.html
{% extends 'expenses/base_generic.html' %}

{% block content %}
<ul>
    {% for i in amount_name_list %}
        <li>{{i.name}} {{i.amt}}</li>
    {% endfor %}
</ul>

{% endblock %}

money_splitter/expenses/templates/expenses/privacy.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy| Splitto-4-Kiddo</title>
    <link rel="shortcut icon" type="image/png" href="./img/money.jpg" />
    <link rel="stylesheet" href="expensestyle.css" />
</head>

<body>
    <header>
        <nav class="nav">
            <img src="./img/money.jpg" alt="Splitto-4-Kiddo logo" class="nav__logo" id="logo" designer="Sam"
                data-version-number="3.0" />
            <ul class="nav__links">
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="../../../users/templates/users/index.html">Home</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="terms.html">Terms of Use</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="about.html">About Us</a>
                </li>
                <li class="nav__item">
                    <a class="nav__link nav__link--btn btn--show-modal" href="blog.html">Blog</a>
                </li>
            </ul>
        </nav>
    </header>
    <h1><u>Privacy Policy</u></h1>
    <div class="blog">
        <ul>
            <li>
                <h3>Information We Collect:</h3>
                <ul>
                    <li>We collect minimal, necessary information to provide our services. This may include user
                        details, transaction data, and other relevant information.</li>
                </ul>
            </li>
            <li>
                <h3>How We Use Your Information:</h3>
                <ul>
                    <li>Your information is used solely for the purpose of facilitating shared expense management on
                        Splitto-4-Kiddo. We do not share or sell your data to third parties.</li>
                </ul>
            </li>
            <li>
                <h3>Data Security:</h3>
                <ul>
                    <li>We employ robust security measures to protect your information from unauthorized access,
                        disclosure, alteration, or destruction.</li>
                </ul>
            </li>
            <li>
                <h3>Cookies:</h3>
                <ul>
                    <li>Splitto-4-Kiddo may use cookies to enhance user experience. Users can manage cookie preferences
                        in their browser settings.</li>
                </ul>
            </li>
            <li>
                <h3>Third-Party Links:</h3>
                <ul>
                    <li>Our platform may contain links to third-party websites. We are not responsible for the privacy
                        practices of these external sites.</li>
                </ul>
            </li>
            <li>
                <h3>Updates to Privacy Policy:</h3>
                <ul>
                    <li>We reserve the right to update our Privacy Policy. Users will be notified of any changes.</li>
                </ul>
            </li>
            <li>
                <h3>User Control:</h3>
                <ul>
                    <li>Users have the right to access, correct, or delete their personal information stored on
                        Splitto-4-Kiddo.</li>
                </ul>
            </li>
        </ul>
        <p class="para">
            By using our platform, you agree to this Privacy Policy. We value your privacy and are committed to maintaining
            the confidentiality and security of your information. If you have any questions or concerns, please contact us
            at [contact@splitto4kiddo.com]. Thank you for choosing Splitto-4-Kiddo!
        </p>
    </div>



</body>

</html>

money_splitter/expenses/templates/expenses/split_expense.html
{% extends "expenses/base_generic.html" %}

{% block content %}
  <h1>Expense Split</h1>
  <h3>Paid by : {{ppp}}</h3>
  <h3>Total amount : {{ Total.amount }}</h3>
 <h3>Payment made at : {{Total.created_at}}</h3>
  <table>
    <thead>
      <tr>
        <th>Owes</th>
        <th>Owed To</th>
        <th>Amount</th>
      </tr>
    </thead>
    <tbody>
      {% for expense in payments %}
        <tr>
          {% if expense.paid_by_names != ppp %}
          <td>{{ expense.paid_by_names }}</td>
          <td>{{ ppp }}</td>
          <td>{{ expense.amount }}</td>
          {% endif %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}